
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Visual Studio 2022/Visual Studio 2022 IDE/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:12 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
